name: VMF CI

on: [push, pull_request]

jobs:
  
  build-linux:
    strategy:
      matrix:
        jdkVersion: [11, 17, 18, 19-ea]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdkVersion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdkVersion }}
        architecture: x64 # (x64 or x86)
    
    - name: Build and test with Gradle/JUnit
      run:  sh ./build-and-test-all.sh

      
  build-macos-latest:
    strategy:
      matrix:
        jdkVersion: [11]
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdkVersion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdkVersion }}
        architecture: x64 # (x64 or x86)
        
    - name: Build and test with Gradle/JUnit
      run:  sh ./build-and-test-all.sh 
   
  build-windows-latest:
    strategy:
      matrix:
        jdkVersion: [11, 17, 18, 19-ea]
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdkVersion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdkVersion }}
        architecture: x64 # (x64 or x86)
   
    - name: Build and test with Gradle/JUnit
      run:  ./build-and-test-all.bat
